[package]
name = "procstat"
version = "0.1.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "procstat"
path = "src/main.rs"

[dependencies]
axum = "0.7.2"
bounded-vec-deque = "0.1.1"
chrono = "0.4.31"
clap = { version = "4.4.11", features = ["derive"] }
ctrlc = "3.4.1"
futures = "0.3.30"
image = "0.24.7"
once_cell = "1.19.0"
plotters = "0.3.5"
proc_sys_parser = "0.1.8"
sysctl = "0.5.5"
tokio = { version = "1.35.0", features = ["full"] }

[package.metadata.generate-rpm]
assets = [
    { source = "target/release/procstat", dest = "/usr/local/bin/procstat", mode="0755" }
]
release = "1.el8"

[package.metadata.deb]
copyright = "2021, Frits Hoogland <fhoogland@gmail.com>"
maintainer = "Frits Hoogland <fhoogland@gmail.com>"
depends = "$auto"
section = "utility"
priority = "optional"
assets = [
    ["target/release/procstat", "/usr/local/bin/", "755"]
]
