[package]
name = "procstat"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proc_sys_parser = "0.1.2"
tokio = { version = "1.35.0", features = ["full"] }
